language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kolsone/docker-react -f Dockerfile.dev .

script:
  docker run -e CI=true kolsone/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-990014633396"
  bucket_path: "docker-react-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



